
name: Build website

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Install system dependencies
        run: sudo apt-get install libvips-tools

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Build site
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true
          jekyll_src: .

      - name: Build site second time for Tailwind
        uses: limjh16/jekyll-action-ts@v2
        with:
          enable_cache: true
          format_output: true
          jekyll_src: .

      - name: "Publish site"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
